name: Tutorial Install Test
on:
  push:
  schedule:
    # Run once per day at 00:00 UTC
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: List contents of repository
      run: ls -al

    - name: Pre-build dev container image
      uses: devcontainers/ci@v0.3
      with:
        push: never
        runCmd: echo "Dev container is working correctly"

    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-build-artifact
        path: path/to/artifact

    - name: Check for errors
      if: ${{ steps.devcontainer.outcome != 'success' }}
      run: |
        echo "An error occurred while running the Dev Container Build and Run action"
        exit 1
