name: Tutorial Install Tests
on:
  push:
  schedule:
    # Run once per day at 00:00 UTC
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: List contents of repository
        run: ls -al

      - name: TestBuild
        id: tb
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: echo "Dev container is working correctly"
        
      - name: Print outcome
        run: echo ${{steps.tb.outcome}}
    
      - name: Check for errors
        if: steps.tb.outcome != 'success' }}
        run: |
          echo "An error occurred while running the Dev Container Build and Run action"
          exit 1
